
server:
  port: 80

spring:
  servlet:
    multipart:
      enabled: false
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/osvaldo
    username: xenon
    password: xenon
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update


